export * from './AtualizarMarcadorRequestModel';
export * from './BaseMarcaModel';
export * from './BaseMarcadorModel';
export * from './CriarMarcaModelResponse';
export * from './CriarMarcadorRequestModel';
export * from './ListagemMarcasResponseModel';
export * from './MarcaRequestModel';
export * from './MarcaResponseModel';
export * from './ObterMarcadorResponseModel';

export * from './AtualizarMarcadorRequestModel';
export * from './BaseMarcadorModel';
export * from './BaseMarcaModel';
export * from './CriarMarcadorRequestModel';
export * from './CriarMarcaModelResponse';
export * from './ListagemMarcasResponseModel';
export * from './MarcaRequestModel';
export * from './MarcaResponseModel';
export * from './ObterMarcadorResponseModel';
